Repository study-pals/backend, pull requests merged in 2025-05, with the labels that each got.

#71 [#61][BUGFIX] 그룹 가입 통합 테스트 오류 수정
  src/test/java/com/studypals/integrationTest/GroupEntryIntegrationTest.java
Labels: 🐛 bugfix

#75 [#74][CICD] url 및 테스트 데이터베이스 이전
  Jenkinsfile
  build.gradle
Labels: :building_construction: cicd

#77 [#76][FEATURE] study time 테이블을 id-type 방식으로 변환
  src/main/java/com/studypals/domain/studyManage/dao/StudyTimeRepository.java
  src/main/java/com/studypals/domain/studyManage/dto/GetCategoryRes.java
  src/main/java/com/studypals/domain/studyManage/dto/GetStudyDto.java
  src/main/java/com/studypals/domain/studyManage/dto/GetStudyRes.java
  src/main/java/com/studypals/domain/studyManage/dto/StartStudyReq.java
  src/main/java/com/studypals/domain/studyManage/dto/StartStudyRes.java
  src/main/java/com/studypals/domain/studyManage/dto/StudyList.java
  src/main/java/com/studypals/domain/studyManage/dto/mappers/CategoryMapper.java
  src/main/java/com/studypals/domain/studyManage/dto/mappers/StudyTimeMapper.java
  src/main/java/com/studypals/domain/studyManage/entity/StudyStatus.java
  src/main/java/com/studypals/domain/studyManage/entity/StudyTime.java
  src/main/java/com/studypals/domain/studyManage/entity/StudyType.java
  src/main/java/com/studypals/domain/studyManage/facade/StudyTimeFacade.java
  src/main/java/com/studypals/domain/studyManage/facade/strategy/AbstractCategoryBasedStrategy.java
  src/main/java/com/studypals/domain/studyManage/facade/strategy/GroupStudyCategoryRenderStrategy.java
  src/main/java/com/studypals/domain/studyManage/facade/strategy/PersonalCategoryStudyRenderStrategy.java
  src/main/java/com/studypals/domain/studyManage/facade/strategy/StudyRenderStrategy.java
  src/main/java/com/studypals/domain/studyManage/facade/strategy/StudyRenderStrategyFactory.java
  src/main/java/com/studypals/domain/studyManage/facade/strategy/TemporarStudyRenderStrategy.java
  src/main/java/com/studypals/domain/studyManage/service/StudySessionServiceImpl.java
  src/main/java/com/studypals/domain/studyManage/service/StudyTimeServiceImpl.java
  src/main/java/com/studypals/domain/studyManage/worker/DailyInfoWriter.java
  src/main/java/com/studypals/domain/studyManage/worker/StudyCategoryReader.java
  src/main/java/com/studypals/domain/studyManage/worker/StudySessionWorker.java
  src/main/java/com/studypals/domain/studyManage/worker/StudyStatusWorker.java
  src/main/java/com/studypals/domain/studyManage/worker/strategy/AbstractStudyPersistenceStrategy.java
  src/main/java/com/studypals/domain/studyManage/worker/strategy/GroupStudyPersistenceStrategy.java
  src/main/java/com/studypals/domain/studyManage/worker/strategy/PersonalStudyPersistenceStrategy.java
  src/main/java/com/studypals/domain/studyManage/worker/strategy/StudyTimePersistenceStrategy.java
  src/main/java/com/studypals/domain/studyManage/worker/strategy/StudyTimePersistenceStrategyFactory.java
  src/main/java/com/studypals/domain/studyManage/worker/strategy/TemporarStudyPersistenceStrategy.java
  src/main/java/com/studypals/global/exceptions/exceptionHandler/DefaultExceptionHandler.java
  src/main/resources/application-local.properties
  src/test/java/com/studypals/domain/studyManage/dao/StudyTimeRepositoryTest.java
  src/test/java/com/studypals/domain/studyManage/dto/mappers/CategoryMapperTest.java
  src/test/java/com/studypals/domain/studyManage/dto/mappers/StudyTimeMapperTest.java
  src/test/java/com/studypals/domain/studyManage/facade/StudyTimeFacadeTest.java
  src/test/java/com/studypals/domain/studyManage/facade/strategy/CategoryBasedStrategyTest.java
  src/test/java/com/studypals/domain/studyManage/restDocsTest/CategoryControllerRestDocsTest.java
  src/test/java/com/studypals/domain/studyManage/restDocsTest/StudySessionControllerRestDocsTest.java
  src/test/java/com/studypals/domain/studyManage/restDocsTest/StudyTimeControllerRestDocsTest.java
  src/test/java/com/studypals/domain/studyManage/service/DailyStudyInfoServiceTest.java
  src/test/java/com/studypals/domain/studyManage/service/StudyCategoryServiceTest.java
  src/test/java/com/studypals/domain/studyManage/service/StudySessionServiceTest.java
  src/test/java/com/studypals/domain/studyManage/service/StudyTimeServiceTest.java
  src/test/java/com/studypals/domain/studyManage/worker/DailyInfoReaderTest.java
  src/test/java/com/studypals/domain/studyManage/worker/DailyInfoWriterTest.java
  src/test/java/com/studypals/domain/studyManage/worker/StudyCategoryReaderTest.java
  src/test/java/com/studypals/domain/studyManage/worker/StudyCategoryWriterTest.java
  src/test/java/com/studypals/domain/studyManage/worker/StudySessionWorkerTest.java
  src/test/java/com/studypals/domain/studyManage/worker/StudyStatusWorkerTest.java
  src/test/java/com/studypals/domain/studyManage/worker/strategy/CategoryBaseStudyPersistenceStrategyTest.java
  src/test/java/com/studypals/domain/studyManage/worker/strategy/StudyTimePersistenceStrategyFactoryTest.java
  src/test/java/com/studypals/integrationTest/StudySessionIntegrationTest.java
  src/test/java/com/studypals/integrationTest/StudyTimeIntegrationTest.java
Labels: ♻️ refactor

#83 [FEATURE][#79] 그룹 오늘의 목표 API 구현
  src/main/java/com/studypals/domain/groupManage/api/GroupStudyController.java
  src/main/java/com/studypals/domain/groupManage/dao/GroupStudyCategoryRepository.java
  src/main/java/com/studypals/domain/groupManage/dto/DailySuccessRateDto.java
  src/main/java/com/studypals/domain/groupManage/dto/DailySuccessRateRes.java
  src/main/java/com/studypals/domain/groupManage/dto/GetGroupCategoryRes.java
  src/main/java/com/studypals/domain/groupManage/dto/GroupMemberProfileImageDto.java
  src/main/java/com/studypals/domain/groupManage/dto/GroupSummaryRes.java
  src/main/java/com/studypals/domain/groupManage/dto/GroupTotalStudyDto.java
  src/main/java/com/studypals/domain/groupManage/entity/GroupStudyCategory.java
  src/main/java/com/studypals/domain/groupManage/entity/GroupStudyCategoryType.java
  src/main/java/com/studypals/domain/groupManage/service/GroupStudyCategoryService.java
  src/main/java/com/studypals/domain/groupManage/service/GroupStudyCategoryServiceImpl.java
  src/main/java/com/studypals/domain/groupManage/util/GroupStudyStatisticCalculator.java
  src/main/java/com/studypals/domain/groupManage/worker/GroupStudyCategoryReader.java
  src/main/java/com/studypals/domain/groupManage/worker/strategy/AbstractGroupCategoryStrategy.java
  src/main/java/com/studypals/domain/groupManage/worker/strategy/GroupCategoryStrategy.java
  src/main/java/com/studypals/domain/groupManage/worker/strategy/GroupCategoryStrategyFactory.java
  src/main/java/com/studypals/domain/groupManage/worker/strategy/GroupDailyCategoryStrategy.java
  src/main/java/com/studypals/domain/groupManage/worker/strategy/GroupWeeklyCategoryStrategy.java
  src/main/java/com/studypals/domain/studyManage/dao/StudyTimeRepository.java
  src/main/java/com/studypals/domain/studyManage/dto/GroupTypeDto.java
  src/main/java/com/studypals/domain/studyManage/service/StudyTimeServiceImpl.java
  src/main/java/com/studypals/domain/studyManage/worker/StudyTimeReader.java
  src/main/java/com/studypals/global/exceptions/errorCode/GroupErrorCode.java
  src/main/java/com/studypals/global/responses/ResponseCode.java
  src/test/java/com/studypals/domain/groupManage/restDocsTest/GroupEntryControllerRestDocsTest.java
  src/test/java/com/studypals/domain/groupManage/restDocsTest/GroupStudyControllerRestDocsTest.java
  src/test/java/com/studypals/domain/groupManage/service/GroupEntryServiceTest.java
  src/test/java/com/studypals/domain/groupManage/service/GroupStudyCategoryServiceTest.java
  src/test/java/com/studypals/domain/groupManage/util/GroupStudyStatisticCalculatorTest.java
  src/test/java/com/studypals/domain/groupManage/worker/GroupStudyCategoryReaderTest.java
  src/test/java/com/studypals/domain/groupManage/worker/strategy/GroupDailyCategoryStrategyTest.java
  src/test/java/com/studypals/domain/groupManage/worker/strategy/GroupWeeklyCategoryStrategyTest.java
  src/test/java/com/studypals/domain/studyManage/service/StudyTimeServiceTest.java
  src/test/java/com/studypals/domain/studyManage/worker/StudyTimeReaderTest.java
  src/test/java/com/studypals/integrationTest/GroupStudyIntegrationTest.java
Labels: ✨ feature

#89 [#88][FEATURE] Redis 기반 JPA 스타일 HashRepository 구현
  build.gradle
  src/main/java/com/studypals/global/redis/RedisConfig.java
  src/main/java/com/studypals/global/redis/redisHashRepository/EntityMeta.java
  src/main/java/com/studypals/global/redis/redisHashRepository/RedisEntityMapper.java
  src/main/java/com/studypals/global/redis/redisHashRepository/RedisEntityMetadataReader.java
  src/main/java/com/studypals/global/redis/redisHashRepository/RedisHashEntityInformation.java
  src/main/java/com/studypals/global/redis/redisHashRepository/RedisHashRepositoriesRegistrar.java
  src/main/java/com/studypals/global/redis/redisHashRepository/RedisHashRepository.java
  src/main/java/com/studypals/global/redis/redisHashRepository/RedisHashRepositoryFactory.java
  src/main/java/com/studypals/global/redis/redisHashRepository/RedisHashRepositoryFactoryBean.java
  src/main/java/com/studypals/global/redis/redisHashRepository/RedisLuaQuery.java
  src/main/java/com/studypals/global/redis/redisHashRepository/SimpleRedisHashRepository.java
  src/main/java/com/studypals/global/redis/redisHashRepository/annotations/EnableRedisHashRepositories.java
  src/main/java/com/studypals/global/redis/redisHashRepository/annotations/Expires.java
  src/main/java/com/studypals/global/redis/redisHashRepository/annotations/LuaQuery.java
  src/main/java/com/studypals/global/redis/redisHashRepository/annotations/RedisHashEntity.java
  src/main/java/com/studypals/global/redis/redisHashRepository/annotations/RedisHashMapField.java
  src/main/java/com/studypals/global/redis/redisHashRepository/annotations/RedisId.java
  src/main/resources/application.properties
  src/test/java/com/studypals/global/redis/redisHashRepository/RedisHashRepositoryTest.java
  src/test/java/com/studypals/testModules/testComponent/TestRedisHashEntity.java
  src/test/java/com/studypals/testModules/testComponent/TestRedisHashRepository.java
Labels: ✨ feature
