Repository study-pals/backend, pull requests merged in 2025-04, with the labels that each got.

#29 [#18] [FEATURE] spotless 적용
  .gitignore
  build.gradle
  script/pre-commit
  src/main/java/com/studypals/StudyPalsApplication.java
  src/main/java/com/studypals/domain/memberManage/api/AuthController.java
  src/main/java/com/studypals/domain/memberManage/dao/MemberRepository.java
  src/main/java/com/studypals/domain/memberManage/dao/RefreshTokenRedisRepository.java
  src/main/java/com/studypals/domain/memberManage/dto/CreateMemberReq.java
  src/main/java/com/studypals/domain/memberManage/dto/CreateRefreshTokenDto.java
  src/main/java/com/studypals/domain/memberManage/dto/ReissueTokenRes.java
  src/main/java/com/studypals/domain/memberManage/dto/SignInReq.java
  src/main/java/com/studypals/domain/memberManage/dto/TokenReissueReq.java
  src/main/java/com/studypals/domain/memberManage/entity/Member.java
  src/main/java/com/studypals/domain/memberManage/entity/MemberDetails.java
  src/main/java/com/studypals/domain/memberManage/entity/RefreshToken.java
  src/main/java/com/studypals/domain/memberManage/service/MemberDetailsService.java
  src/main/java/com/studypals/domain/memberManage/service/MemberService.java
  src/main/java/com/studypals/domain/memberManage/service/MemberServiceImpl.java
  src/main/java/com/studypals/domain/memberManage/service/SignInService.java
  src/main/java/com/studypals/domain/memberManage/service/SignInServiceImpl.java
  src/main/java/com/studypals/domain/memberManage/service/TokenService.java
  src/main/java/com/studypals/domain/memberManage/service/TokenServiceImpl.java
  src/main/java/com/studypals/global/configs/JpaAuditingConfig.java
  src/main/java/com/studypals/global/exceptions/errorCode/AuthErrorCode.java
  src/main/java/com/studypals/global/exceptions/errorCode/ErrorCode.java
  src/main/java/com/studypals/global/exceptions/errorCode/GroupErrorCode.java
  src/main/java/com/studypals/global/exceptions/errorCode/StudyErrorCode.java
  src/main/java/com/studypals/global/exceptions/exception/AuthException.java
  src/main/java/com/studypals/global/exceptions/exception/BaseException.java
  src/main/java/com/studypals/global/exceptions/exception/GroupException.java
  src/main/java/com/studypals/global/exceptions/exception/StudyException.java
  src/main/java/com/studypals/global/exceptions/exceptionHandler/DefaultExceptionHandler.java
  src/main/java/com/studypals/global/exceptions/exceptionHandler/ExceptionHandlerOrder.java
  src/main/java/com/studypals/global/exceptions/exceptionHandler/GlobalExceptionHandler.java
  src/main/java/com/studypals/global/redis/RedisConfig.java
  src/main/java/com/studypals/global/redis/RedisRepository.java
  src/main/java/com/studypals/global/redis/RedisSaveBuilder.java
  src/main/java/com/studypals/global/responses/CommonResponse.java
  src/main/java/com/studypals/global/responses/Response.java
  src/main/java/com/studypals/global/responses/ResponseCode.java
  src/main/java/com/studypals/global/security/config/AccessURL.java
  src/main/java/com/studypals/global/security/config/SecurityConfig.java
  src/main/java/com/studypals/global/security/jwt/JwtAuthenticationFilter.java
  src/main/java/com/studypals/global/security/jwt/JwtToken.java
  src/main/java/com/studypals/global/security/jwt/JwtUtils.java
  src/test/java/com/studypals/StudyPalsApplicationTests.java
  src/test/java/com/studypals/global/exceptions/exceptionHandler/GlobalExceptionHandlerTest.java
  src/test/java/com/studypals/testModules/restDocs/RestDocsConfig.java
  src/test/java/com/studypals/testModules/testComponent/TestController.java
  src/test/java/com/studypals/testModules/testComponent/TestErrorCode.java
  src/test/java/com/studypals/testModules/testComponent/TestException.java
  src/test/java/com/studypals/testModules/testUtils/JsonFieldResultMatcher.java
Labels: ✨ feature

#32 [#31][HOTFIX] spotless java format 변경
  build.gradle
  src/main/java/com/studypals/domain/memberManage/api/AuthController.java
  src/main/java/com/studypals/domain/memberManage/entity/RefreshToken.java
  src/main/java/com/studypals/domain/memberManage/service/MemberDetailsService.java
  src/main/java/com/studypals/domain/memberManage/service/MemberServiceImpl.java
  src/main/java/com/studypals/domain/memberManage/service/SignInService.java
  src/main/java/com/studypals/domain/memberManage/service/SignInServiceImpl.java
  src/main/java/com/studypals/domain/memberManage/service/TokenServiceImpl.java
  src/main/java/com/studypals/global/exceptions/errorCode/GroupErrorCode.java
  src/main/java/com/studypals/global/exceptions/errorCode/StudyErrorCode.java
  src/main/java/com/studypals/global/exceptions/exceptionHandler/DefaultExceptionHandler.java
  src/main/java/com/studypals/global/security/config/SecurityConfig.java
  src/main/java/com/studypals/global/security/jwt/JwtAuthenticationFilter.java
  src/main/java/com/studypals/global/security/jwt/JwtUtils.java
  src/test/java/com/studypals/global/exceptions/exceptionHandler/GlobalExceptionHandlerTest.java
  src/test/java/com/studypals/testModules/restDocs/RestDocsConfig.java
  src/test/java/com/studypals/testModules/testUtils/JsonFieldResultMatcher.java
Labels: 🚑 hotfix

#41 [#34][FEATURE] category / study /redis dao 및 테스트
  build.gradle
  src/main/java/com/studypals/domain/memberManage/dao/MemberRepository.java
  src/main/java/com/studypals/domain/memberManage/entity/Member.java
  src/main/java/com/studypals/domain/studyManage/dao/StudyCategoryRepository.java
  src/main/java/com/studypals/domain/studyManage/dao/StudyStatusRedisRepository.java
  src/main/java/com/studypals/domain/studyManage/dao/StudyTimeRepository.java
  src/main/java/com/studypals/domain/studyManage/entity/StudyCategory.java
  src/main/java/com/studypals/domain/studyManage/entity/StudyStatus.java
  src/main/java/com/studypals/domain/studyManage/entity/StudyTime.java
  src/main/java/com/studypals/global/redis/RedisConfig.java
  src/main/java/com/studypals/global/security/jwt/JwtToken.java
  src/test/java/com/studypals/domain/studyManage/dao/StudyCategoryRepositoryTest.java
  src/test/java/com/studypals/domain/studyManage/dao/StudyStatusRedisRepositoryTest.java
  src/test/java/com/studypals/domain/studyManage/dao/StudyTimeRepositoryTest.java
Labels: ✨ feature

#40 [#24][FEATURE] minio 이미지 저장 로직 구현
  build.gradle
  src/main/java/com/studypals/domain/common/fileManage/FilePath.java
  src/main/java/com/studypals/domain/common/fileManage/ObjectStorage.java
  src/main/java/com/studypals/domain/common/fileManage/dao/AbstractFileRepository.java
  src/main/java/com/studypals/global/minio/MinioConfig.java
  src/main/java/com/studypals/global/minio/MinioStorage.java
  src/main/java/com/studypals/global/responses/ResponseCode.java
  src/main/java/com/studypals/global/utils/ImageUtils.java
  src/main/resources/application.properties
Labels: ✨ feature

#45 [#42][TEST] MinIO 업로드, 삭제 테스트
  src/main/java/com/studypals/domain/common/fileManage/dao/AbstractFileRepository.java
  src/test/java/com/studypals/domain/common/fileManage/dao/AbstractFileRepositoryTest.java
  src/test/java/com/studypals/global/minio/MinioStorageTest.java
Labels: 🧪 test

#47 [#35][FEATURE] 카테고리(토픽) 도메인 / 테스트
  build.gradle
  src/asciidoc/api/study.adoc
  src/asciidoc/index.adoc
  src/main/java/com/studypals/domain/studyManage/StudyConstant.java
  src/main/java/com/studypals/domain/studyManage/api/CategoryController.java
  src/main/java/com/studypals/domain/studyManage/dao/StudyCategoryRepository.java
  src/main/java/com/studypals/domain/studyManage/dto/CreateCategoryReq.java
  src/main/java/com/studypals/domain/studyManage/dto/GetCategoryRes.java
  src/main/java/com/studypals/domain/studyManage/dto/UpdateCategoryReq.java
  src/main/java/com/studypals/domain/studyManage/dto/mappers/CategoryMapper.java
  src/main/java/com/studypals/domain/studyManage/entity/StudyCategory.java
  src/main/java/com/studypals/domain/studyManage/service/StudyCategoryService.java
  src/main/java/com/studypals/domain/studyManage/service/StudyCategoryServiceImpl.java
  src/main/java/com/studypals/global/exceptions/exception/GroupException.java
  src/main/java/com/studypals/global/exceptions/exception/StudyException.java
  src/main/resources/application.properties
  src/test/java/com/studypals/domain/studyManage/dao/StudyCategoryRepositoryTest.java
  src/test/java/com/studypals/domain/studyManage/restDocsTest/CategoryControllerRestDocsTest.java
  src/test/java/com/studypals/domain/studyManage/service/StudyCategoryServiceTest.java
  src/test/java/com/studypals/integrationTest/CategoryIntegrationTest.java
  src/test/java/com/studypals/testModules/testUtils/JsonFieldResultMatcher.java
  src/test/resources/application-test.properties
Labels: ✨ feature

#52 [#46][FEATURE] 그룹 생성 구현
  src/asciidoc/api/group.adoc
  src/main/java/com/studypals/domain/groupManage/api/GroupController.java
  src/main/java/com/studypals/domain/groupManage/dao/GroupMemberRepository.java
  src/main/java/com/studypals/domain/groupManage/dao/GroupRepository.java
  src/main/java/com/studypals/domain/groupManage/dao/GroupTagRepository.java
  src/main/java/com/studypals/domain/groupManage/dto/CreateGroupReq.java
  src/main/java/com/studypals/domain/groupManage/dto/GetGroupTagRes.java
  src/main/java/com/studypals/domain/groupManage/dto/mappers/GroupMapper.java
  src/main/java/com/studypals/domain/groupManage/dto/mappers/GroupMemberMapper.java
  src/main/java/com/studypals/domain/groupManage/entity/Group.java
  src/main/java/com/studypals/domain/groupManage/entity/GroupMember.java
  src/main/java/com/studypals/domain/groupManage/entity/GroupRole.java
  src/main/java/com/studypals/domain/groupManage/entity/GroupTag.java
  src/main/java/com/studypals/domain/groupManage/service/GroupService.java
  src/main/java/com/studypals/domain/groupManage/service/GroupServiceImpl.java
  src/main/java/com/studypals/global/dao/ReadOnlyRepository.java
  src/main/java/com/studypals/global/responses/ResponseCode.java
  src/main/resources/application.properties
  src/test/java/com/studypals/domain/groupManage/restDocsTest/GroupControllerRestDocsTest.java
  src/test/java/com/studypals/domain/groupManage/service/GroupServiceTest.java
  src/test/java/com/studypals/integrationTest/GroupIntegrationTest.java
Labels: ✨ feature

#56 [#55][REFACTOR] 그룹 생성 코드 리팩토링
  src/main/java/com/studypals/domain/groupManage/service/GroupServiceImpl.java
  src/main/java/com/studypals/domain/groupManage/worker/GroupMemberWorker.java
  src/main/java/com/studypals/domain/groupManage/worker/GroupReader.java
  src/main/java/com/studypals/domain/groupManage/worker/GroupWorker.java
  src/main/java/com/studypals/global/annotations/Facade.java
  src/main/java/com/studypals/global/annotations/Worker.java
  src/main/java/com/studypals/global/exceptions/errorCode/GroupErrorCode.java
  src/main/java/com/studypals/global/responses/ResponseCode.java
  src/test/java/com/studypals/domain/groupManage/service/GroupServiceTest.java
  src/test/java/com/studypals/domain/groupManage/worker/GroupMemberWorkerTest.java
  src/test/java/com/studypals/domain/groupManage/worker/GroupReaderTest.java
  src/test/java/com/studypals/domain/groupManage/worker/GroupWorkerTest.java
Labels: ♻️ refactor

#57 [#50][FEATURE] 그룹 초대 코드 생성 구현
  src/asciidoc/api/group.adoc
  src/main/java/com/studypals/domain/groupManage/api/GroupController.java
  src/main/java/com/studypals/domain/groupManage/dao/GroupEntryCodeRedisRepository.java
  src/main/java/com/studypals/domain/groupManage/dao/GroupMemberRepository.java
  src/main/java/com/studypals/domain/groupManage/dto/GroupEntryCodeRes.java
  src/main/java/com/studypals/domain/groupManage/entity/Group.java
  src/main/java/com/studypals/domain/groupManage/entity/GroupEntryCode.java
  src/main/java/com/studypals/domain/groupManage/entity/GroupMember.java
  src/main/java/com/studypals/domain/groupManage/service/GroupService.java
  src/main/java/com/studypals/domain/groupManage/service/GroupServiceImpl.java
  src/main/java/com/studypals/domain/groupManage/worker/GroupAuthorityValidator.java
  src/main/java/com/studypals/domain/groupManage/worker/GroupEntryCodeGenerator.java
  src/main/java/com/studypals/domain/groupManage/worker/GroupReader.java
  src/main/java/com/studypals/global/exceptions/errorCode/GroupErrorCode.java
  src/main/java/com/studypals/global/redis/RedisConfig.java
  src/main/java/com/studypals/global/responses/ResponseCode.java
  src/main/java/com/studypals/global/utils/RandomUtils.java
  src/test/java/com/studypals/domain/groupManage/restDocsTest/GroupControllerRestDocsTest.java
  src/test/java/com/studypals/domain/groupManage/service/GroupServiceTest.java
  src/test/java/com/studypals/domain/groupManage/worker/GroupAuthorityValidatorTest.java
  src/test/java/com/studypals/domain/groupManage/worker/GroupEntryCodeGeneratorTest.java
  src/test/java/com/studypals/integrationTest/GroupIntegrationTest.java
Labels: ✨ feature

#62 [#37][FEATURE] 특정 기간 간 공부 시간 반환
  src/asciidoc/api/study.adoc
  src/main/java/com/studypals/domain/groupManage/dto/mappers/GroupMapper.java
  src/main/java/com/studypals/domain/groupManage/entity/Group.java
  src/main/java/com/studypals/domain/memberManage/dto/mappers/MemberMapper.java
  src/main/java/com/studypals/domain/memberManage/entity/Member.java
  src/main/java/com/studypals/domain/studyManage/api/StudySessionController.java
  src/main/java/com/studypals/domain/studyManage/api/StudyTimeController.java
  src/main/java/com/studypals/domain/studyManage/dao/DailyStudyInfoRepository.java
  src/main/java/com/studypals/domain/studyManage/dao/StudyTimeRepository.java
  src/main/java/com/studypals/domain/studyManage/dto/EndStudyReq.java
  src/main/java/com/studypals/domain/studyManage/dto/GetDailyStudyDto.java
  src/main/java/com/studypals/domain/studyManage/dto/GetDailyStudyInfoDto.java
  src/main/java/com/studypals/domain/studyManage/dto/GetDailyStudyRes.java
  src/main/java/com/studypals/domain/studyManage/dto/PeriodDto.java
  src/main/java/com/studypals/domain/studyManage/dto/StartStudyReq.java
  src/main/java/com/studypals/domain/studyManage/dto/StudyList.java
  src/main/java/com/studypals/domain/studyManage/dto/mappers/DailyStudyInfoMapper.java
  src/main/java/com/studypals/domain/studyManage/entity/DailyStudyInfo.java
  src/main/java/com/studypals/domain/studyManage/entity/StudyTime.java
  src/main/java/com/studypals/domain/studyManage/facade/StudyTimeFacade.java
  src/main/java/com/studypals/domain/studyManage/service/DailyStudyInfoService.java
  src/main/java/com/studypals/domain/studyManage/service/DailyStudyInfoServiceImpl.java
  src/main/java/com/studypals/domain/studyManage/service/StudySessionService.java
  src/main/java/com/studypals/domain/studyManage/service/StudySessionServiceImpl.java
  src/main/java/com/studypals/domain/studyManage/service/StudyTimeService.java
  src/main/java/com/studypals/domain/studyManage/service/StudyTimeServiceImpl.java
  src/main/java/com/studypals/domain/studyManage/worker/DailyInfoReader.java
  src/main/java/com/studypals/domain/studyManage/worker/DailyInfoWriter.java
  src/main/java/com/studypals/domain/studyManage/worker/StudySessionWorker.java
  src/main/java/com/studypals/domain/studyManage/worker/StudyStatusWorker.java
  src/main/java/com/studypals/domain/studyManage/worker/StudyTimeReader.java
  src/main/resources/application.properties
  src/test/java/com/studypals/domain/studyManage/dao/DailyStudyInfoRepositoryTest.java
  src/test/java/com/studypals/domain/studyManage/dao/StudyTimeRepositoryTest.java
  src/test/java/com/studypals/domain/studyManage/dto/mappers/CategoryMapperTest.java
  src/test/java/com/studypals/domain/studyManage/dto/mappers/DailyStudyInfoMapperTest.java
  src/test/java/com/studypals/domain/studyManage/dto/mappers/StudyTimeMapperTest.java
  src/test/java/com/studypals/domain/studyManage/restDocsTest/StudySessionControllerRestDocsTest.java
  src/test/java/com/studypals/domain/studyManage/restDocsTest/StudyTimeControllerRestDocsTest.java
  src/test/java/com/studypals/domain/studyManage/service/DailyStudyInfoServiceTest.java
  src/test/java/com/studypals/domain/studyManage/service/StudySessionServiceTest.java
  src/test/java/com/studypals/domain/studyManage/service/StudyTimeServiceTest.java
  src/test/java/com/studypals/domain/studyManage/worker/StudySessionWorkerTest.java
  src/test/java/com/studypals/domain/studyManage/worker/StudyStatusWorkerTest.java
  src/test/java/com/studypals/domain/studyManage/worker/StudyTimeReaderTest.java
  src/test/java/com/studypals/integrationTest/StudyTimeIntegrationTest.java
Labels: ✨ feature

#63 [HOTFIX] 빌드 실패 오류 수정
  src/test/java/com/studypals/domain/studyManage/restDocsTest/StudyTimeControllerRestDocsTest.java
Labels: 🚑 hotfix
